name: Deploy project to Azure

on:
  push:
    branches: [master]
    
env:
  publish_name: widget_co
  dotnet_version: '6.x'
  project_file:  './widget_co/CloudDatabase.csproj'
  configuration: 'release'
  out_path: './output'

# Deploy project
jobs:
  build-base:
    runs-on: ubuntu-latest
    environment: dev
    steps: 
    - name: checkout
      uses: actions/checkout@master

    - name: login azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 

    - name: set dotNet environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet_version }}

    - name: restore 
      run: dotnet restore ${{ env.project_file }}

    - name: build
      run: dotnet build -c ${{ env.configuration }} ${{ env.project_file }} --no-restore

    - name: publish
      shell: bash
      run: |
        pushd './${{ env.publish_name }}'
        dotnet build --configuration ${{ env.configuration }} --output ${{ env.out_path }}
        popd
    - name: push remote
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.publish_name }}
        package: '${{ env.publish_name }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}