name: Deploy Azure Resources master

on:
  push:
    branches: [master]
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: login into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - name: deploy bicep template 
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\.github\workflows\deploy\deployResources.ps1
          azPSVersion: "latest"